yamada-ui/yamada-docs

contents/getting-started/advanced.ja.mdx
contents/getting-started/advanced.mdx
contents/getting-started/basics.ja.mdx
contents/getting-started/basics.mdx
contents/getting-started/frameworks/nextjs/app-router.ja.mdx
contents/getting-started/frameworks/nextjs/app-router.mdx
contents/getting-started/installation/index.mdx
contents/getting-started/installation/individual.ja.mdx
contents/getting-started/installation/individual.mdx
contents/getting-started/installation/minimal.ja.mdx
contents/getting-started/installation/minimal.mdx
contents/styled-system/theming/customize-theme.mdx

build: updated doc

---

contents/getting-started/basics.ja.mdx
contents/getting-started/basics.mdx
contents/styled-system/semantic-tokens.ja.mdx
contents/styled-system/semantic-tokens.mdx
contents/styled-system/theming/customize-theme.ja.mdx
contents/styled-system/theming/customize-theme.mdx
contents/styled-system/theming/default-theme.ja.mdx
contents/styled-system/theming/default-theme.mdx

style: updated link color to blue

---

contents/getting-started/frameworks/vite.ja.mdx
contents/getting-started/frameworks/vite.mdx

Closes #145 
> Added description page in Vite.
> Nothing.
> Nothing.
No.

Add getting started with vite page.

---

components/mdx/package-managers.tsx
contents/getting-started/frameworks/create-react-app.ja.mdx
contents/getting-started/frameworks/create-react-app.mdx
contents/getting-started/frameworks/nextjs/app-router.ja.mdx
contents/getting-started/frameworks/nextjs/app-router.mdx
contents/getting-started/frameworks/nextjs/index.ja.mdx
contents/getting-started/frameworks/nextjs/index.mdx
contents/getting-started/frameworks/vite.ja.mdx
contents/getting-started/frameworks/vite.mdx

Closes #156  
> Make `PackageManagers` support `bun`.
> Nothing.
> Nothing.
No.

Supported `bun` in `PackageManagers`

---

contents/hooks/use-theme.ja.mdx
contents/hooks/use-theme.mdx

fix: fixed URL

---

contents/getting-started/frameworks/remix.ja.mdx
contents/getting-started/frameworks/remix.mdx

Closes #148 
added two pages:
* `/getting-started/frameworks/remix` ... `Getting Started with Remix`
* `/ja/getting-started/frameworks/remix` ... `Getting Started with Remix (in Japanese)`

Docs/add `Getting Started with Remix`

---

contents/getting-started/frameworks/gatsby.ja.mdx
contents/getting-started/frameworks/gatsby.mdx

Closes #147
add 2 pasges in Docs
- Gatting Started with Gatsby (in English)
- Gatting Started with Gatsby (in Japanese)
In English
[![Image from Gyazo](https://i.gyazo.com/14a299b0516a80158704380f29dcfb14.gif)](https://gyazo.com/14a299b0516a80158704380f29dcfb14)
In japanese
[![Image from Gyazo](https://i.gyazo.com/42d1026ef7aa5d75aec856bca89db291.gif)](https://gyazo.com/42d1026ef7aa5d75aec856bca89db291)
No
No

[WIP]Docs:add Gatting Started with Gatsby 

---

.github/workflows/observe.yml
package.json
scripts/observe-issues.ts
scripts/observe-pull-requests.ts

Added observe GitHub Actions
No

Added observe GitHub Actions

---

contents/components/data-display/resizable/index.ja.mdx
contents/components/data-display/resizable/index.mdx

Closes #169
Added warning notes.
No

Updated warning notes in `Resizable`

---

contents/styled-system/ui.ja.mdx
contents/styled-system/ui.mdx

Added `shouldForwardProp` and `disableStyleProp` description to `ui`.

Added `shouldForwardProp` and `disableStyleProp` description

---

contents/hooks/use-snacks.mdx

Closes # 
Fixed the `useSnacks` description.
No

chore(use-snacks): fix description in `useSnacks` hook

---

contents/components/forms/textarea/index.ja.mdx
contents/components/forms/textarea/index.mdx

Closes #191
Add a note on the use of resizeRef.
NIL
NIL
No

feat(textarea): add resizeRef documentation

---

CONTRIBUTING.ja.md
CONTRIBUTING.md

Closes #197 
Add link for test tips.
No
No

add test tips

---

constant/core-members.ts

* Update my display name
* Fix my twitter ID

[Core Member] Update koralle's profile

---

scripts/changelog.ts
scripts/component-props.ts
scripts/style-props.ts
scripts/theme-component.ts

Added dynamic git branch handling
No

Feat switch branch to scripts

---

contents/getting-started/basics.ja.mdx
contents/getting-started/basics.mdx
contents/hooks/use-loading.ja.mdx
contents/hooks/use-loading.mdx

Updated custom loading links
No

Updated custom loading links

---

contents/components/overlay/drawer/index.ja.mdx
contents/components/overlay/drawer/index.mdx

Closes #216 
Added `closeOnDrag` prop example in document.
No

Added `closeOnDrag` prop example in document

---

components/forms/search.tsx
components/layouts/header.tsx

Closes #230 
Adds a search icon for mobile view.
No

Add a search icon for mobile view

---

contents/styled-system/responsive-styles.ja.mdx
contents/styled-system/responsive-styles.mdx

Closes #235
Made `md` in the Responsive Styles documentation lowercase.
It was written in uppercase.
It is now in lowercase.
No

Made `md` in the Responsive Styles documentation lowercase

---

contents/components/feedback/bar-chart/index.ja.mdx
contents/components/feedback/bar-chart/index.mdx

Closes #224
Add `BarChart` document.
No

Added `BarChart`

---

pages/examples/cards/AccountCard.tsx
pages/examples/cards/BookmarkCard.tsx
pages/examples/cards/CookieSettingsCard.tsx
pages/examples/cards/GitHubCard.tsx
pages/examples/cards/ImageCard.tsx
pages/examples/cards/NotificationCard.tsx
pages/examples/cards/OverflowImageCard.tsx
pages/examples/cards/PaymentMethodCard.tsx
pages/examples/cards/PickDateCard.tsx
pages/examples/cards/ReportIssueCard.tsx
pages/examples/cards/ShareDocumentCard.tsx
pages/examples/cards/SocialMediaCard.tsx
pages/examples/cards/StatCard.tsx
pages/examples/cards/TeamMembersCard.tsx
pages/examples/cards/UserCard.tsx
pages/examples/cards/index.tsx

Closes #206 
Created an example page for `cards`.
No

Created an example page for `cards`

---

pages/examples/playground/editor/index.tsx
pages/examples/playground/editor/menu.tsx
pages/examples/playground/editor/model.tsx
pages/examples/playground/editor/parameter.tsx
pages/examples/playground/editor/prompt.tsx
pages/examples/playground/editor/switch-mode/complete-icon.tsx
pages/examples/playground/editor/switch-mode/edit-icon.tsx
pages/examples/playground/editor/switch-mode/index.tsx
pages/examples/playground/editor/switch-mode/insert-icon.tsx
pages/examples/playground/footer/index.tsx
pages/examples/playground/header/control-button.tsx
pages/examples/playground/header/delete-dialog.tsx
pages/examples/playground/header/filter-modal.tsx
pages/examples/playground/header/index.tsx
pages/examples/playground/header/preset.tsx
pages/examples/playground/header/save-modal.tsx
pages/examples/playground/header/share-button.tsx
pages/examples/playground/header/view-code-modal.tsx
pages/examples/playground/index.tsx

Closes #208
Added `Playground` example page.
No

Added `Playground` example

---

contents/components/feedback/area-chart/index.ja.mdx
contents/components/feedback/area-chart/index.mdx
contents/components/feedback/bar-chart/index.ja.mdx
contents/components/feedback/bar-chart/index.mdx
contents/components/feedback/line-chart/index.ja.mdx
contents/components/feedback/line-chart/index.mdx

Simplified syncId prop usage.
No

Simplified syncId prop usage

---

contents/getting-started/frameworks/create-react-app.ja.mdx
contents/getting-started/frameworks/create-react-app.mdx
contents/getting-started/frameworks/gatsby.ja.mdx
contents/getting-started/frameworks/gatsby.mdx
contents/getting-started/frameworks/hono.ja.mdx
contents/getting-started/frameworks/hono.mdx
contents/getting-started/frameworks/nextjs/app-router.ja.mdx
contents/getting-started/frameworks/nextjs/app-router.mdx
contents/getting-started/frameworks/nextjs/index.ja.mdx
contents/getting-started/frameworks/nextjs/index.mdx
contents/getting-started/frameworks/remix.ja.mdx
contents/getting-started/frameworks/remix.mdx
contents/getting-started/frameworks/vite.ja.mdx
contents/getting-started/frameworks/vite.mdx
contents/getting-started/installation/index.ja.mdx
contents/getting-started/installation/index.mdx
contents/hooks/use-window-event.ja.mdx
contents/hooks/use-window-event.mdx
contents/styled-system/at-rules.ja.mdx
contents/styled-system/at-rules.mdx

Added @yamada-ui/charts component.
No

Added @yamada-ui/charts component info

---

contents/components/overlay/drawer/index.ja.mdx
contents/components/overlay/drawer/index.mdx
i18n/content.en.json
i18n/content.ja.json

Added guide to hide drag bar in drawer
No

Added guide to hide drag bar in drawer

---

contents/styled-system/color-mode.mdx

Closes #252
Added English translation to `Color Mode` documentation.
No

Added English translation to `Color Mode` documentation.

---

pages/examples/mail/MailDetail.tsx
pages/examples/mail/MailHeader.tsx
pages/examples/mail/MailInbox.tsx
pages/examples/mail/MailSidebar.tsx
pages/examples/mail/data.ts
pages/examples/mail/date.ts
pages/examples/mail/index.tsx

Closes #204 
> Crated an example page for `Mail`
No
wip

Crated an example page for `Mail`

---

components/media-and-icons/seo.tsx
constant/seo.ts
pages/index.page.tsx

Closes #249
Add metadata for each pages.
No

Add metadata for each pages

---

contents/components/data-display/card/index.ja.mdx
contents/components/data-display/card/index.mdx
contents/components/layouts/aspect-ratio/index.ja.mdx
contents/components/layouts/aspect-ratio/index.mdx

Closes #259
Closes #257
Updated content with "SLAM DUNK" references.
No

Updated content with "SLAM DUNK" references

---

contents/getting-started/frameworks/hono.ja.mdx
contents/getting-started/frameworks/hono.mdx

Closes #265
The sample that is now in the documentation flushes when reloading.
Replaced with modified code.
The sample that is now in the documentation flushes when reloading.
Fixed sample code to not flash on reload.
No

Added description to prevent flashing

---

contents/components/overlay/menu/index.ja.mdx
contents/components/overlay/menu/index.mdx

Closes #271
Updated `MenuGroup` attribute to `label`.
No

Updated `MenuGroup` attribute to `label`

---

i18n/content.en.json
i18n/content.ja.json

…n' to 'article' in en and ja content files
close #280 
Closes # 

fix: Update Card component description

---

pages/examples/dashboard/header-bottom.tsx
pages/examples/dashboard/header-top.tsx
pages/examples/dashboard/index.tsx
pages/examples/dashboard/item-card.tsx
pages/examples/dashboard/item.tsx
pages/examples/dashboard/name-card.tsx
pages/examples/dashboard/overview.tsx
pages/examples/dashboard/recent-sales.tsx

feat(dashboard): add example page of dashboard
